---
title: "script_climate"
author: "Julian Mittmann-Goetsch"
date: "2025-04-17"
output: html_document
---

# Versionlog
## Version 1.0: Basic script with data loading - 17.04.2025 | JM
## Version 1.1: Streamlined script - 02.06.2025 | JM

# Step 1: Prepare R session
## Step 1a: Install necessary packages
```{r}
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("ggpubr")
#install.packages("here")
#install.packages("lubridate")
#install.packages("tidyverse")
```

## Step 1b: Load all necessary packages
```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(here)
library(lubridate)
library(tidyverse)
```

## Step 1c: Set global plot theme
```{r}
# Creates a theme for all plots in this study 
theme_JM <- theme(
  axis.title.x      = element_text(colour = "black", size = 12),
  axis.text.x       = element_text(colour = "black", size = 12), 
  axis.title.y      = element_text(colour = "black", size = 12),
  axis.text.y       = element_text(colour = "black", size = 12), 
  legend.title      = element_text(colour = "black", size = 12),
  legend.text       = element_text(colour = "black", size = 12), 
  legend.position   = "top",
  panel.background  = element_blank(), 
  panel.border      = element_rect(colour = "black", fill = NA, size = 1.2),
  legend.key        = element_blank(),
  strip.text.x      = element_text(colour = "black", size = 12),
  strip.text.y      = element_text(colour = "black", size = 12)
)
```

## Step 1d: Load raw data (source DWD)
```{r}
df_precipitation_08 <- read.delim(here("data", "climate", "regional_averages_rr_08.txt"), dec = ".", sep = ";", skip = 1)
df_temperature_08 <- read.delim(here("data", "climate", "regional_averages_tm_08.txt"), dec = ".", sep = ";", skip = 1)
```

## Step 1e: Merge raw data
```{r}
df_precipitation_08 <- df_precipitation_08 %>%
  select(Year = Jahr, Month = Monat, Precipitation = Schleswig.Holstein)

df_temperature_08 <- df_temperature_08 %>%
  select(Year = Jahr, Month = Monat, Temperature = Schleswig.Holstein)

df_climate_08 <- df_precipitation_08 %>%
  left_join(df_temperature_08, by = c("Year", "Month"))
```

# Step 2: Plot climate data
```{r}
max_temp <- max(df_climate_08$Temperature, na.rm = TRUE)
max_precip <- max(df_climate_08$Precipitation, na.rm = TRUE)
scaling_factor <- max_temp / max_precip

plot_climate_08 <- df_climate_08 %>%
  filter(Year > 2001 & Year < 2023) %>%
  ggplot(aes(x = Year)) +
  geom_col(aes(y = Precipitation * scaling_factor), 
           width = 0.7, 
           fill = "steelblue",
           alpha = 0.6) +
  geom_line(aes(y = Temperature), color = "red", linewidth = 1) +
  scale_y_continuous(
    name = "Mean monthly temperature [°C]",
    sec.axis = sec_axis(~./scaling_factor, 
                        name = "Mean monthly precipitation [mm]")
  ) +
  scale_x_continuous(breaks = seq(2002, 2022, by = 2)) +
  labs(x = "Year") +
  theme_JM +
  theme(axis.title.y.right = element_text(color = "steelblue"),
        axis.text.y.right = element_text(color = "steelblue"))
```

# References
```{r}
# dplyr: Wickham, H., François, R., Henry, L., Müller, K., Vaughan, D., & PBC, P. S. (2024). dplyr: A Grammar of Data Manipulation. R package version 1.1.4. https://CRAN.R-project.org/package=dplyr
# ggplot2: Wickham, H., Chang, W., Henry, L., Pedersen, T. L., Takahashi, K., Wilke, C., Woo, K., & Yutani, H. (2024). ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics. R package version 3.5.1. https://CRAN.R-project.org/package=ggplot2
# ggpubr: Kassambara, A. (2024). ggpubr: 'ggplot2' Based Publication Ready Plots. R package version 0.6.0. https://CRAN.R-project.org/package=ggpubr
# here: Müller, K. & Bryan, J. (2024). here: A Simpler Way to Find Your Files. R package version 1.0.1. https://CRAN.R-project.org/package=here
# lubridate: Spinu, V., Grolemund, G., & Wickham, H. (2024). lubridate: Make Dealing with Dates a Little Easier. R package version 1.9.3. https://CRAN.R-project.org/package=lubridate
# tidyverse: Wickham, H., Bryan, J., François, R., Henry, L., Müller, K., Pedersen, T. L., & Takahashi, K. (2024). tidyverse: Easily Install and Load the 'Tidyverse'. R package version 2.0.0. https://CRAN.R-project.org/package=tidyverse
```
