---
title: "script_DNA_2022"
author: "Julian Mittmann-Goetsch"
date: "2025-01-26"
output: html_document
---

# Versionlog
## Version 1.0: Implementing old scripts (26.01.2025)

# Step 1: Prepare session and load data
## Step 1a: Install necessary packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("tidyverse")       # edit data frames (long format)
#install.packages("ggplot2")         # Plot data (NDMS,)
#install.packages("RStoolbox")       # NDMS 
#install.packages("vegan")           # NDMS
#install.packages("tidyr")           # edit data frames (wide format)
#install.packages("viridis")
#install.packages("ggpubr")          # more themes for ggplot2
#install.packages("RVAideMemoire")   # PERMANOVA post-hoc test
#install.packages("dplyr")           # Summarize function
```

## Step 1b: Load necessary packages
```{r}
library(vegan)
library(tidyverse)
#library(dada2); packageVersion("dada2")
library(ggplot2)
#library(RStoolbox)
library(tidyr)
library(viridis)
library(ggpubr)
library(RVAideMemoire)
library(dplyr)

library(phyloseq)
library(microViz)
```

## Step 1c: Load sequencing data
```{r}
asv_dna <- read.csv("./data/dna/asv_full.csv", dec=".", sep=";")
metadata_dna <- read.csv("./data/dna/samplefile.csv", dec=".", sep=";")
```
## Step 1d: Define plot theme
```{r message=FALSE, warning=FALSE}
# Creates a theme for all plots in this study 
# Creates a theme for all plots in this study 
theme_JM <- theme(axis.title.x        = element_text(colour = "black", size = 12, face = "bold"),
                   axis.text.x        = element_text(colour = "black", size = 12, face = "bold"), 
                   axis.title.y       = element_text(colour = "black", size = 12, face = "bold"),
                   axis.text.y        = element_text(colour = "black", size = 12, face = "bold"), 
                   legend.title       = element_text(colour = "black", size = 12, face = "bold"),
                   legend.text        = element_text(colour = "black", size = 12, face = "bold"), 
                   legend.position    = "top",
                   panel.background   = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
                   legend.key         = element_blank(),
                   strip.text.x       = element_text(colour = "black", size = 12, face = "bold"),
                   strip.text.y       = element_text(colour = "black", size = 12, face = "bold"))
```



# Step 2: Analysis
## Step 2a: Create Phyloseq object
```{r}
asv_dna <- asv_dna %>%
  column_to_rownames(var = "ASVs")

metadata_dna <- metadata_dna  %>%
  mutate_at(c(3:9), as.factor)

df_samp = sample_data(metadata_dna) 
sample_ids <- metadata_dna[, 3]
rownames(df_samp) <- sample_ids

# Phyloseq object with raw data (used for clr transformation)
ps_dna = phyloseq(
    otu_table(as.matrix(asv_dna[,1:(ncol(asv_dna)-7)]), taxa_are_rows=T),
    tax_table(as.matrix(asv_dna[,(ncol(asv_dna)-6):ncol(asv_dna)])),
    sample_data(df_samp)
   )

# Reorder factors of ps element
ps_dna@sam_data[["Zone"]] <- factor(ps_dna@sam_data[["zone"]], levels = c("PZ","LM","HM"))
ps_dna@sam_data[["Treatment"]] <- recode_factor(ps_dna@sam_data[["treatment"]],  "0" = "ambient", "1.5" = "+1.5°C", "3" = "+3.0°C")
```

## Step 2b: NMDS plots
```{r}
#ord_explore(ps_dna)

ps_dna %>%
 tax_transform(rank = "unique", trans = "identity") %>%
 dist_calc(dist = "bray") %>%
 ord_calc(
  method = "NMDS"
 ) %>% 
 ord_plot(
  axes = c(1, 2),
  colour = "Treatment", fill = "Treatment",
  shape = "Zone", alpha = 0.5,
  size = 2
 ) + 
 scale_shape_girafe_filled()

plot_dna_nmds <- ps_dna %>%
 tax_transform(rank = "unique", trans = "identity") %>%
 dist_calc(dist = "bray") %>%
 ord_calc(method = "NMDS") %>% 
 ord_plot(axes = c(1, 2),
  colour = "Treatment", fill = "Treatment",
  shape = "Zone", alpha = 0.5, size = 2) + 
 scale_shape_girafe_filled() +
 geom_polygon(aes(colour = Treatment, fill = Treatment, group = interaction(Treatment, Zone)), alpha = 0.3, show.legend = FALSE) +
 scale_colour_manual(values = c("#4575B4", "#FDAE61","#D73027"), name = "Warming treatment:") +
 scale_fill_manual(values = c("#4575B4", "#FDAE61","#D73027"), name = "Warming treatment:") +
 facet_wrap(~ Zone, ncol = 3) +
 theme_JM

plot_dna_pc <- ps_dna %>%
 tax_transform(rank = "unique", trans = "clr") %>%
 ord_calc(method = "auto") %>% 
 ord_plot(axes = c(1, 2), colour = "Treatment", alpha = 0.75, size = 3) + 
 scale_shape_girafe_filled() +
 geom_polygon(aes(colour = Treatment, fill = Treatment, group = interaction(Treatment, Zone)), alpha = 0.3, show.legend = FALSE) +
 theme_JM +
 geom_xsidedensity(aes(colour = Treatment, fill = Treatment), alpha = 0.5, show.legend = FALSE) +
 geom_ysidedensity(aes(colour = Treatment, fill = Treatment), alpha = 0.5, show.legend = FALSE) +
 scale_colour_manual(values = c("#4575B4", "#FDAE61","#D73027"), name = "Warming treatment:") +
 scale_fill_manual(values = c("#4575B4", "#FDAE61","#D73027"), name = "Warming treatment:") +
 theme(legend.position = "bottom") +
 facet_wrap(~ Zone, ncol = 3)

# All plots
plot_dna_nmds
plot_dna_pc

```

# Step 2: NMDS
## Step 1e: Transform and combine asv table with metadata
```{r}
#### Transform the data frames ####
asv_dna <- asv_dna %>%
  mutate_at(c(2:58), as.character)

# transform into long-format
asv_long <- asv %>%                      
  gather(key = "Sample", value = "count",JMG1,JMG2,JMG3,JMG4,JMG5,JMG6,JMG7,JMG8,JMG9,JMG10,JMG11,JMG12,JMG13,JMG14,JMG15,JMG16,JMG17,JMG18,JMG19,JMG20,JMG21,JMG22,JMG23,JMG24,JMG25,JMG26,JMG27,JMG28,JMG29,JMG30,JMG31,JMG32,JMG33,JMG34,JMG35,JMG36,JMG37,JMG38,JMG39,JMG40,JMG41,JMG42,JMG43,JMG44,JMG45,JMG46,JMG47,JMG48,JMG49,JMG50,JMG51,JMG52,JMG53,JMG54,JMG55,JMG56,JMG57)

# combine asv table with sample file to asv_sample df
asv_sam <- merge(asv_long, samplefile, by = "Sample", all = TRUE)

# transform df to genus format asv_sam_genus
any(is.na(asv_sam$Genus))
any(is.na(asv_sam$Phylum))
any(is.na(asv_sam$count) | asv_sam$count < 0)
asv_sam$count <- as.numeric(asv_sam$count)

# sort by Genus
asv_sam_gen <- reshape(data=asv_sam,  # Name des Datensatzes
                        v.names="count",
                        timevar= "Genus",
                        # messwiederholte Variable (in einer Spalte)
                        idvar="Sample", 
                        # (bestehende) ID-Variable
                        direction="wide")
# sort by Phylum
asv_sam_gen <- reshape(data=asv_sam,  # Name des Datensatzes
                       v.names="count",
                       timevar= "Phylum",
                       # messwiederholte Variable (in einer Spalte)
                       idvar="Sample", 
                       # (bestehende) ID-Variable
                       direction="wide")
names(asv_sam_gen) <- gsub("count.", "", names(asv_sam_gen))

# sort by ASV
asv_sam_gen <- reshape(data=asv_sam,  # Name des Datensatzes
                       v.names="count",
                       timevar= "ASVs",
                       # messwiederholte Variable (in einer Spalte)
                       idvar="Sample", 
                       # (bestehende) ID-Variable
                       direction="wide")
names(asv_sam_gen) <- gsub("count.", "", names(asv_sam_gen))
```

```{r}
#### NMDS Plot ####
#asv_sam_gen <- subset(asv_sam_gen, Sample != "JMG55" & Sample != "JMG56" & Sample != "JMG57")
com = asv_sam_gen[,23:ncol(asv_sam_gen)]
m_com = as.matrix(com)

set.seed(123)
nmds = metaMDS(m_com, distance = "bray", na.rm = TRUE)
nmds

nmds_data <- data.frame(nmds$points, Plant = asv_sam_gen$plant, Treatment = asv_sam_gen$Treatment, Zone = asv_sam_gen$Zone)
nmds_data$Treatment <- as.factor(nmds_data$Treatment)


nmds_data$Zone  <- factor(nmds_data$Zone, levels = c("PZ","LM","HM"))
polygon_colors <-  c("darkgreen","orange","red","chartreuse","blue","lightblue") 

MDS1<-ggplot(nmds_data, aes(x = MDS1, y = MDS2)) +
  geom_point(size=3, aes( shape = Plant, colour = Treatment))+ 
  stat_ellipse(type = "t", level = 0.95, geom = "polygon", aes(fill = Plant), alpha = 0.2) +
  scale_fill_manual(values = polygon_colors) +
  theme(axis.text.y = element_text(colour = "black", size = 12, face = "bold"), 
        axis.text.x = element_text(colour = "black", face = "bold", size = 12), 
        legend.text = element_text(size = 12, face ="bold", colour ="black"), 
        legend.position = "right", axis.title.y = element_text(face = "bold", size = 14), 
        axis.title.x = element_text(face = "bold", size = 14, colour = "black"), 
        legend.title = element_text(size = 14, colour = "black", face = "bold"), 
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
        legend.key=element_blank()) +
  scale_colour_manual(values = c("#4575B4", "#FDAE61","#D73027"))
MDS1+ facet_grid(~Zone)
```

