---
title: "script_bgb"
author: "Julian Mittmann-Goetsch"
date: "2025-02-03"
output: html_document
---

# Versionlog
## Version 1.0: Basic script with barplots (03.02.2025)

# Step 1: Prepare session and load data
## Step 1a: Install necessary packages
```{r}
#install.packages("ggplot2")
#install.packages("tidyverse")
```

## Step 1b: Load necessary packages
```{r}
library(tidyverse)
library(ggplot2)
```

## Step 1c: Load sequencing data
```{r}
df_bgb <- read.delim("./data/bgb/df_bgb_22.txt", dec = ".", sep = "\t")
```

## Step 1d: Define plot theme
```{r message=FALSE, warning=FALSE}
# Creates a theme for all plots in this study 
# Creates a theme for all plots in this study 
theme_JM <- theme(axis.title.x        = element_text(colour = "black", size = 12, face = "bold"),
                   axis.text.x        = element_text(colour = "black", size = 12, face = "bold"), 
                   axis.title.y       = element_text(colour = "black", size = 12, face = "bold"),
                   axis.text.y        = element_text(colour = "black", size = 12, face = "bold"), 
                   legend.title       = element_text(colour = "black", size = 12, face = "bold"),
                   legend.text        = element_text(colour = "black", size = 12, face = "bold"), 
                   legend.position    = "top",
                   panel.background   = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
                   legend.key         = element_blank(),
                   strip.text.x       = element_text(colour = "black", size = 12, face = "bold"),
                   strip.text.y       = element_text(colour = "black", size = 12, face = "bold"))
```

## Step 1e: Data frame modification
```{r}
df_bgb$Treatment <- recode_factor(df_bgb$Treatment, "ambient" = "ambient", "+1.5" = "+1.5°C", "+3.0" = "+3.0°C")
df_bgb$Zone      <- factor(df_bgb$Zone, levels = c("PZ", "LM", "HM"))
```


# Step 2: Plots
## Step 2a: Barplots
```{r}
plot_bgb_22 <- df_bgb %>%
  ggplot(aes(x = Treatment, y = BGB_g_m2, fill = Treatment)) +
    stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9),
                 alpha = 0.9, width = 0.7) +
    stat_summary(fun.data = mean_se, geom = "errorbar",
                 position = position_dodge(width = 0.9), width = 0.25, color = "black") +
    scale_fill_manual(values = c("ambient" = "#4575B4", "+1.5°C" = "#FDAE61", "+3.0°C" = "#D73027"), name = "Warming treatment:") +
    scale_y_continuous(name = expression(paste("Belowground biomass", " ", " [", "g", "*", " ", "m"^-2, "]")), expand = c(0,0)) +
    coord_cartesian(ylim = c(0, 1500)) +
    facet_grid(~ Zone) +
    theme_JM 

plot_bgb_fine_22 <- df_bgb %>%
  ggplot(aes(x = Treatment, y = Fine_roots_g_m2, fill = Treatment)) +
    stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9),
                 alpha = 0.9, width = 0.7) +
    stat_summary(fun.data = mean_se, geom = "errorbar",
                 position = position_dodge(width = 0.9), width = 0.25, color = "black") +
    scale_fill_manual(values = c("ambient" = "#4575B4", "+1.5°C" = "#FDAE61", "+3.0°C" = "#D73027"), name = "Warming treatment:") +
    scale_y_continuous(name = expression(paste("Fine-root biomass", " ", " [", "g", "*", " ", "m"^-2, "]")), expand = c(0,0)) +
    coord_cartesian(ylim = c(0, 1000)) +
    facet_grid(~ Zone) +
    theme_JM 

plot_bgb_rhizome_22 <- df_bgb %>%
  ggplot(aes(x = Treatment, y = Rhizome_g_m2, fill = Treatment)) +
    stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9),
                 alpha = 0.9, width = 0.7) +
    stat_summary(fun.data = mean_se, geom = "errorbar",
                 position = position_dodge(width = 0.9), width = 0.25, color = "black") +
    scale_fill_manual(values = c("ambient" = "#4575B4", "+1.5°C" = "#FDAE61", "+3.0°C" = "#D73027"), name = "Warming treatment:") +
    scale_y_continuous(name = expression(paste("Rhizome biomass", " ", " [", "g", "*", " ", "m"^-2, "]")), expand = c(0,0)) +
    coord_cartesian(ylim = c(0, 1000)) +
    facet_grid(~ Zone) +
    theme_JM 

plot_bgb_ratio_22 <- df_bgb %>%
  ggplot(aes(x = Treatment, y = Rhiz_fine, fill = Treatment)) +
    stat_summary(fun = mean, geom = "bar", position = position_dodge(width = 0.9),
                 alpha = 0.9, width = 0.7) +
    stat_summary(fun.data = mean_se, geom = "errorbar",
                 position = position_dodge(width = 0.9), width = 0.25, color = "black") +
    scale_fill_manual(values = c("ambient" = "#4575B4", "+1.5°C" = "#FDAE61", "+3.0°C" = "#D73027"), name = "Warming treatment:") +
    scale_y_continuous(name = expression(paste("Rhizome : fine-roots ratio")), expand = c(0,0)) +
    coord_cartesian(ylim = c(0, 1)) +
    facet_grid(~ Zone) +
    theme_JM 

# All plots:
plot_bgb_22
plot_bgb_fine_22
plot_bgb_rhizome_22
plot_bgb_ratio_22

ggarrange(plot_bgb_22, plot_bgb_fine_22, plot_bgb_rhizome_22, plot_bgb_ratio_22)
```


# Step 3: Statistics
```{r}
# First, create a new column for the plot ID, to account for non-independence of samples from the same Plot
df_bgb <- df_bgb %>%
  mutate(plot_id = substr(Plot, 1, 3))


# Model for BGB 
model_bgb <- lme(BGB_g_m2 ~ Treatment * Zone + (1|plot_id), 
                data = df_bgb)

# Model for rhizome fine root ratio
model_rhiz_fine <- lmer(Rhiz_fine ~ Treatment * Zone + (1|plot_id), 
                data = df_bgb)

# ANOVA tables
anova_bgb <- Anova(model_bgb, type = 3)
anova_rhiz_fine <- Anova(model_rhiz_fine, type = 3)

# Print ANOVA results
print(anova_bgb)
print(anova_rhiz_fine)

# If you want post-hoc tests for significant effects:
emm_bgb <- emmeans(model_bgb, ~ Treatment | Zone)
emm_rhiz_fine <- emmeans(model_rhiz_fine, ~ Treatment | Zone)

# Pairwise comparisons
pairs_bgb <- pairs(emm_bgb)
pairs_rhiz_fine <- pairs(emm_rhiz_fine)

# Print pairwise comparisons
print(pairs_bgb)
print(pairs_rhiz_fine)
```
```

# References
```{r}
# References 
```{r}
# R Studio
# R Core Team (2024). R: A Language and Environment for Statistical Computing. https://www.R-project.org/

# ggplot2
# Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York http://link.springer.com/10.1007/978-0-387-98141-3

# dplyr
#Wickham, H., François, R., Henry, L., Müller, K., Vaughan, D., & PBC, P. S. (2023). dplyr: A Grammar of Data Manipulation. R Package Version 1.1.4 Computer Software. https://doi.org/10.32614/CRAN.package.dplyr
```


