---
title: "script_faprotax"
author: "Julian Mittmann-Goetsch"
date: "2025-01-31"
output: html_document
---

## Version 1.0: Basic script using FAPROTAX output table - 31.01.2025 | JM

# Step 1: Prepare session and load data
## Step 1a: Install necessary packages
```{r, message=FALSE, warning=FALSE}
#install.packages("broom")
#install.packages("dplyr")
#install.packages("emmeans")
#install.packages("ggplot2")
#install.packages("ggh4x")
#install.packages("here")
#install.packages("multcompView")
#install.packages("purrr")
#install.packages("tidyverse")
```

## Step 1b: Load necessary packages
```{r}
library(broom)
library(dplyr)
library(emmeans)
library(ggplot2)
library(ggh4x)
library(here)
library(multcompView)
library(purrr)
library(tidyverse)
```

## Step 1c: Load sequencing data
```{r}
df_functional <- read.delim(here::here("data", "faprotax", "df_functional_database.tsv"), dec = ".", sep = "\t")
df_metadata <-  read.delim(here::here("data", "metadata.txt"), dec = ".", sep= "\t")
```

## Step 1d: Modify dataframes
```{r}
df_metadata$Sample_ID <- as.factor(df_metadata$sample_name)

df_metadata <- df_metadata %>%
 # rename("sample_name" = "Sample_ID") %>%
  mutate(Layer = case_when(
    Depth %in% c("0-5 cm", "5-10 cm", "20-30 cm") ~ "Topsoil (0-30 cm)",
    Depth %in% c("40-50 cm", "80-100 cm") ~ "Subsoil (40-100 cm)",
    TRUE ~ NA_character_  # For unexpected values
  ))
df_metadata <- df_metadata %>%
  mutate_at(c(5:9), as.factor)

df_metadata$Zone <- dplyr::recode(df_metadata$Zone,
  "PZ" = "Pioneer zone",
  "LM" = "Low marsh",
  "HM" = "High marsh"
)
df_metadata$Zone <- factor(df_metadata$Zone, levels = c("Pioneer zone", "Low marsh", "High marsh"))
```

```{r}
# Assuming df_functional has Sample_IDs as column names
df_functional_long <- df_functional %>%
  pivot_longer(cols = -X.group, names_to = "Sample_ID", values_to = "abundance")

df_functional_long$Functional <- df_functional_long$X.group

# Merge with metadata
df_merged <- df_functional_long %>%
  inner_join(df_metadata, by = "Sample_ID")

# Reorder Factors
df_merged <- df_merged %>%
  mutate(Treatment = case_when(
    Treatment == "ambient" ~ "Ambient",
    Treatment == "1.5" ~ "+1.5°C",
    Treatment == "3" ~ "+3.0°C",
    TRUE ~ Treatment
  )) %>%
  mutate(Treatment = factor(Treatment, levels = c("Ambient", "+1.5°C", "+3.0°C"))) %>%
  mutate(Zone = factor(Zone, levels = c("Pioneer zone", "Low marsh", "High marsh"),
                      labels = c("Pioneer zone", "Low marsh", "High marsh")))
```


# Step 2: Plots
## Step 2a: Heatmaps
```{r}
# Filter out functional groups containing "human"
df_merged_filtered <- df_merged %>%
  filter(!str_detect(Functional, regex("human", ignore_case = TRUE)))

desired_functions_redox <- c(
  "methanogenesis_by_CO2_reduction_with_H2",
  "methanogenesis_by_reduction_of_methyl_compounds_with_H2",
  "hydrogenotrophic_methanogenesis",
  "methanogenesis",
  "nitrogen_fixation",
  "nitrification",
  "denitrification",
  "sulfate_respiration",
  "methanotrophy",
  "dark_hydrogen_oxidation",
  "fermentation",
  "aerobic_chemoheterotrophy",
  "dark_iron_oxidation",
  "iron_respiration"
)

desired_functions_degradation <- c(
  "cellulolysis",
  "chitinolysis",
  "ligninolysis",
  "hydrocarbon_degradation",
 # "fermentation",
  "aliphatic_non_methane_hydrocarbon_degradation",
  "aromatic_hydrocarbon_degradation",
  "aromatic_compound_degradation"
)

desired_functions_all <- c(
  "aerobic_chemoheterotrophy",
  "photoautotrophy",
  "nitrite_respiration",
  "nitrate_reduction",
  "aerobic_nitrite_oxidation",
  "hydrocarbon_degradation",
  "fermentation",
  "sulfate_respiration",
  "xylanolysis",
  "chitinolysis",
  "cellulolysis",
  "methanotrophy",
  "aerobic_ammonia_oxidation",
  "anoxygenic_photoautotrophy",
  "nitrate_denitrification",
  "dark_hydrogen_oxidation",
  "urelolysis",
  "dark_sulfite_oxidation",
  "dark_sulfur_oxidation",
  "dark_oxidation_of_sulfur_compounds",
  "dark_sulfide_oxidation",
  "animal_parasites_or_symbionts",
  "nitrate_respiration",
  "methanol_oxidation",
  "methylotrophy",
  "methanogenesis",
  "methanogenesis_by_CO2_reduction_with_H2",
  "methanogenesis_by_reduction_of_methyl_compounds_with_H2",
  "hydrogenotrophic_methanogenesis",
  "dark_iron_oxidation",
  "iron_respiration"
)

df_merged_filtered_redox <- df_merged_filtered %>%
  filter(Functional %in% desired_functions_redox)

df_merged_filtered_degradation <- df_merged_filtered %>%
  filter(Functional %in% desired_functions_degradation)

df_merged_filtered_all <- df_merged_filtered %>%
  filter(Functional %in% desired_functions_all)

# Calculate mean abundance for each combination
df_heatmap_redox <- df_merged_filtered_redox %>%
  group_by(Functional, Zone, Treatment) %>%
  summarise(mean_abundance = mean(abundance, na.rm = TRUE)) %>%
  ungroup()

# Calculate mean abundance for each combination
df_heatmap_degradation <- df_merged_filtered_degradation %>%
  group_by(Functional, Zone, Treatment) %>%
  summarise(mean_abundance = mean(abundance, na.rm = TRUE)) %>%
  ungroup()

df_heatmap_degradation_layer <- df_merged_filtered_degradation %>%
  group_by(Functional, Zone, Treatment, Layer) %>%
  summarise(mean_abundance = mean(abundance, na.rm = TRUE)) %>%
  ungroup()

# Calculate mean abundance for each combination
df_heatmap_all <- df_merged_filtered_all %>%
  group_by(Functional, Zone, Treatment) %>%
  summarise(mean_abundance = mean(abundance, na.rm = TRUE)) %>%
  ungroup()

# Create the heatmap with zones side by side and shared y-axis
# Define the custom color palette
custom_palette <- c("#e0ecf4", "#8c96c6", "#810f7c")
custom_palette_2 <- c("#d0d1e6", "#a6bddb", "#023858")


# Modify plot_heatmap_functional_redox
plot_heatmap_functional_redox <- ggplot(df_heatmap_redox, aes(x = Treatment, y = Functional, fill = mean_abundance)) +
  geom_tile() +
  facet_grid(. ~ Zone, scales = "free_x", space = "free_x") +
  scale_fill_gradientn(name = "Mean Abundance", 
                       colors = custom_palette,
                       values = scales::rescale(c(min(df_heatmap_redox$mean_abundance),
                                                  median(df_heatmap_redox$mean_abundance),
                                                  max(df_heatmap_redox$mean_abundance)))) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 6),
    strip.background = element_rect(fill = "lightgrey"),
    strip.text = element_text(face = "bold"),
    panel.spacing = unit(0.1, "lines"),
    axis.title.y = element_text(margin = margin(r = 10))
  ) +
  labs(x = "Treatment", y = "Functional Group", 
       title = "Functional Group Abundance Across Zones and Treatments (Redox)")

# Modify plot_heatmap_functional_degradation
plot_heatmap_functional_degradation <- ggplot(df_heatmap_degradation, aes(x = Treatment, y = Functional, fill = mean_abundance)) +
  geom_tile() +
  facet_grid(. ~ Zone, scales = "free_x", space = "free_x") +
  scale_fill_gradientn(
    name = "Mean Abundance",
    colors = custom_palette_2,
    values = scales::rescale(c(min(df_heatmap_degradation$mean_abundance),
                               median(df_heatmap_degradation$mean_abundance),
                               max(df_heatmap_degradation$mean_abundance))),
    breaks = pretty(df_heatmap_degradation$mean_abundance, n = 5),
    guide = guide_colorbar(barwidth = 12, barheight = 1.2, title.position = "top", title.hjust = 0.5)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    strip.background = element_rect(fill = "lightgrey"),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom",
    panel.spacing = unit(0.1, "lines"),
    axis.title.y = element_text(margin = margin(r = 10))
  ) +
  labs(x = "Treatment", y = "Functional Group") +
  scale_y_discrete(labels = function(x) stringr::str_to_sentence(gsub("_", " ", x)))

# Modify plot_heatmap_functional_degradation with Layers
plot_heatmap_functional_degradation_layer <- ggplot(df_heatmap_degradation_layer, aes(x = Treatment, y = Functional, fill = mean_abundance)) +
  geom_tile() +
  facet_grid(. ~ Zone * Layer, scales = "free_x", space = "free_x") +
  scale_fill_gradientn(
    name = "Mean Abundance",
    colors = custom_palette_2,
    values = scales::rescale(c(min(df_heatmap_degradation$mean_abundance),
                               median(df_heatmap_degradation$mean_abundance),
                               max(df_heatmap_degradation$mean_abundance))),
    breaks = pretty(df_heatmap_degradation$mean_abundance, n = 5),
    guide = guide_colorbar(barwidth = 12, barheight = 1.2, title.position = "top", title.hjust = 0.5)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    strip.background = element_rect(fill = "lightgrey"),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom",
    panel.spacing = unit(0.1, "lines"),
    axis.title.y = element_text(margin = margin(r = 10))
  ) +
  labs(x = "Treatment", y = "Functional Group") +
  scale_y_discrete(labels = function(x) stringr::str_to_sentence(gsub("_", " ", x)))

# Modify plot_heatmap_functional_all
plot_heatmap_functional_all <- ggplot(df_heatmap_all, aes(x = Treatment, y = Functional, fill = mean_abundance)) +
  geom_tile() +
  facet_grid(. ~ Zone, scales = "free_x", space = "free_x") +
  scale_fill_gradientn(
    name = "Mean Abundance",
    colors = custom_palette_2,
    values = scales::rescale(c(min(df_heatmap_all$mean_abundance),
                               median(df_heatmap_all$mean_abundance),
                               max(df_heatmap_all$mean_abundance))),
    breaks = pretty(df_heatmap_all$mean_abundance, n = 5),
    guide = guide_colorbar(barwidth = 12, barheight = 1.2, title.position = "top", title.hjust = 0.5)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    strip.background = element_rect(fill = "lightgrey"),
    strip.text = element_text(face = "bold"),
    panel.spacing = unit(0.1, "lines"),
    axis.title.y = element_text(margin = margin(r = 10))
  ) +
  labs(x = "Treatment", y = "Functional Group") +
  scale_y_discrete(labels = function(x) stringr::str_to_sentence(gsub("_", " ", x)))


# Display the plots
plot_heatmap_functional_redox
plot_heatmap_functional_degradation
plot_heatmap_functional_all

```

# References
```{r}
# broom: Robinson, D., Hayes, A., Couch, S., & González, I. (2024). broom: Convert Statistical Analysis Objects into Tidy Tibbles. R package version 1.0.5. https://CRAN.R-project.org/package=broom
# dplyr: Wickham, H., François, R., Henry, L., Müller, K., Vaughan, D., & PBC, P. S. (2024). dplyr: A Grammar of Data Manipulation. R package version 1.1.4. https://CRAN.R-project.org/package=dplyr
# emmeans: Lenth, R. V. (2024). emmeans: Estimated Marginal Means, aka Least-Squares Means. R package version 1.10.2. https://CRAN.R-project.org/package=emmeans
# ggplot2: Wickham, H., Chang, W., Henry, L., Pedersen, T. L., Takahashi, K., Wilke, C., Woo, K., & Yutani, H. (2024). ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics. R package version 3.5.1. https://CRAN.R-project.org/package=ggplot2
# ggh4x: van den Brand, T. (2024). ggh4x: Hacks for 'ggplot2'. R package version 0.2.7. https://CRAN.R-project.org/package=ggh4x
# here: Müller, K. & Bryan, J. (2024). here: A Simpler Way to Find Your Files. R package version 1.0.1. https://CRAN.R-project.org/package=here
# multcompView: Graves, S., Piepho, H.-P., Selzer, L., & Dorai-Raj, S. (2024). multcompView: Visualizations of Paired Comparisons. R package version 0.2-10. https://CRAN.R-project.org/package=multcompView
# purrr: Henry, L. & Wickham, H. (2024). purrr: Functional Programming Tools. R package version 1.0.2. https://CRAN.R-project.org/package=purrr
# tidyverse: Wickham, H., Bryan, J., François, R., Henry, L., Müller, K., Pedersen, T. L., & Takahashi, K. (2024). tidyverse: Easily Install and Load the 'Tidyverse'. R package version 2.0.0. https://CRAN.R-project.org/package=tidyverse
```


